---
name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: make some reports
        uses: binjafan/workflows.ga/.github/workflows/actions/generate-report.yaml@main

      - name: restore cache
        uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-{{ hashFiles('**/package*.json') }}

      - name: make cache if it does not exists
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: build application
        run: npm run build --if-present
